version: '3.8'
services:
    honeygain:
        container_name: honeygain
        image: honeygain/honeygain
        command: -tou-accept -email $EMAIL -pass $HONEYGAIN_PASSWORD -device $DEVICE_NAME
        restart: unless-stopped
