version: '3.3'
services:
    ## HONEYGAIN
    honeygain:
        container_name: honeygain
        image: honeygain/honeygain
        command: -tou-accept -email $EMAIL -pass $HONEYGAIN_PASSWORD -device $DEVICE_NAME
        restart: unless-stopped
    ## REPOCKET
    repocket:
        container_name: repocket
        image: repocket/repocket:arm64
        environment:
            - RP_EMAIL=$EMAIL
            - RP_PASSWORD=$REPOCKET_PASSWORD
        restart: always
    ## PACKETSTREAM - NO FUNCIONA EN LA PI ZERO
    Packetstream:
        container_name: packetstream
        image: packetstream/psclient:latest
        environment:
            - CID=$PACKETSTREAM_CID
        restart: always
        
    ## TRAFF MONETIZER
    TraffMonetizer:
        container_name: traffmonetizer
        image: traffmonetizer/cli:arm32v7
        command: start accept status --token ${TRAFFMONETIZER_ID} --device-name $DEVICE_NAME
        environment:
            - TRAFFMONETIZER_DUMMY=''
        restart: always
        
    ## Peer2Profit    
    Peer2profit:
        container_name: peer2profit
        image: peer2profit/peer2profit_linux:latest
        environment:
            - P2P_EMAIL=$EMAIL
        restart: always

    ## Pawns    
    Pawns:
        container_name: Pawns
        image: iproyal/pawns-cli:latest
        command: '-email=${EMAIL} -password=${PAWNS_PWD} -device-name=${DEVICE_NAME} -device-id=${DEVICE_ID} -accept-tos'
        restart: always
